import { createClient } from '@supabase/supabase-js';

// Get environment variables (works in Next.js and Node scripts)
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || '';

if (!supabaseUrl) {
  throw new Error('Missing NEXT_PUBLIC_SUPABASE_URL environment variable');
}

if (!supabaseAnonKey) {
  throw new Error('Missing NEXT_PUBLIC_SUPABASE_ANON_KEY environment variable');
}

// Client-side Supabase client (uses anon key)
export const supabase = createClient(supabaseUrl, supabaseAnonKey);

// Server-side Supabase client (uses service role key for admin operations)
export const supabaseAdmin = createClient(
  supabaseUrl,
  supabaseServiceKey || supabaseAnonKey, // Fallback to anon key if service key not available
  {
    auth: {
      autoRefreshToken: false,
      persistSession: false
    }
  }
);

// Database types (will be auto-generated by Supabase CLI later)
export interface Vehicle {
  id: string;
  vin: string;
  year: number;
  make: string;
  model: string;
  trim?: string;
  price: number;
  miles?: number;
  condition?: string;
  body_style?: string;
  primary_image_url: string;
  total_photos?: number;
  transmission?: string;
  fuel_type?: string;
  drive_type?: string;
  exterior_color?: string;
  interior_color?: string;
  mpg_city?: number;
  mpg_highway?: number;
  doors?: number;
  cylinders?: number;
  description?: string;
  features?: string[];
  options?: string;
  dealer_id: string;
  dealer_name: string;
  dealer_address?: string;
  dealer_city?: string;
  dealer_state?: string;
  dealer_zip?: string;
  dealer_vdp_url: string;
  is_active?: boolean;
  last_sync?: string;
  created_at?: string;
  latitude?: number;
  longitude?: number;
  targeting_radius?: number;
  /** Designated Marketing Area from LotLinx (consolidates 414 cities to ~50 DMAs) */
  dma?: string;
  /** Certified Pre-Owned status from LotLinx (NOT NULL DEFAULT false in DB) */
  certified: boolean;
  /** Days on lot from LotLinx (0 = newly added, null = unknown, validated >= 0 by parser) */
  dol?: number;
}

// PostGIS spatial query response (includes distance calculation)
export interface VehicleWithDistance extends Vehicle {
  distance_miles: number; // Distance in miles from PostGIS ST_Distance
  total_results: number; // Total count of matching records (from window function)
}

export interface Click {
  id: string;
  vehicle_id: string;
  dealer_id: string;
  user_id: string;
  session_id?: string;
  is_billable: boolean;
  cta_clicked?: string;
  utm_source?: string;
  utm_medium?: string;
  utm_campaign?: string;
  created_at: string;
}

export interface DealerClickHistory {
  id: string;
  user_id: string;
  dealer_id: string;
  first_click_at: string;
  last_click_at: string;
  click_count: number;
}

export interface Impression {
  id: string;
  vehicle_id: string;
  page_type?: string;
  user_id?: string;
  session_id?: string;
  created_at: string;
}
